### ISSUE TITLE
Failed to connect to session bus

### ISSUE THREAD

**Issue by ozboss** [flathub/dev.lizardbyte.app.Sunshine#10]
Running the command
`sudo -i PULSE_SERVER=unix:$(pactl info | awk '/Server String/{print$3}') flatpak run dev.lizardbyte.app.Sunshine`
results in the error message:
`Failed to connect to session bus: Failed to execute child process ?dbus-launch? (No such file or directory)`

Running without sudo works fine, but fails to gain CAP_SYS_ADMIN:
`Error: Failed to gain CAP_SYS_ADMIN`

I made sure to run these commands before:
`sudo chown $USER /dev/uinput && echo 'KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/85-sunshine-input.rules`
`sudo flatpak override --talk-name=org.freedesktop.Flatpak dev.lizardbyte.app.Sunshine`

My system is running Fedora 38.

**Comment by istori1** [comment]
The error for `Failed to connect to session bus` is related to the Sunshine tray icon unable to connect to the session bus (user level). When running Sunshine with root the user session bus is unavailable.

The error `Failed to gain CAP_SYS_ADMIN` won't be possible to fix due to how Flatpak is designed. This error can be ignored by running Sunshine as root.

**Comment by ozboss** [comment]
Thanks for the clarification, this is not all that bad then.
What is bad is that the call with `sudo`  causes other issues. For example runnning on KDE it is not possible with Sunshine to call `kscreen-doctor` to adjust the screen resolution before starting the stream. I tried running it with `runuser` but it also does not work.
Is there any way to obtain `CAP_SYS_ADMIN` without `sudo` or circumvent it all together?

**Comment by ReenigneArcher** [comment]
There is no known way to solve this due to the way flatpak sandboxes apps.
