### ISSUE TITLE
This flathub is not officially maintained

### ISSUE THREAD

**Issue by osalbahr** [flathub/dev.lizardbyte.app.Sunshine#11]
The name in this repo will remain as it is, since this is what we publish to the releases available on github. The flathub sunshine is not officially maintained at this point.

_Originally posted by @ReenigneArcher in https://github.com/LizardByte/Sunshine/issues/1369#issuecomment-1590095540_
            

Should it be removed from flathub?

**Comment by ReenigneArcher** [comment]
This is not depreciated... It's just not officially maintained. It is maintained by a trusted member of our community though.

You just have to realize that the usage of this version will have its own documentation. The sunshine docs cover the flatpak packages that we publish to the official repo.

**Comment by osalbahr** [comment]
I found it confusing finding it in Flathub not knowing I shouldn't install it. Maybe a warning in the page?

**Comment by ReenigneArcher** [comment]
This package is now officially maintained. I don't plan on making any changes to the current package (unless a break fix is needed), but starting with next stable release this package will match exactly what upstream publishes.
