### ISSUE TITLE
Summary shouldn't end with full stop

### ISSUE THREAD

**Issue by razzeee** [flathub/dev.lizardbyte.app.Sunshine#15]

**Comment by ReenigneArcher** [comment]
I'm closing this until more details are provided.

**Comment by razzeee** [comment]
Feel free to ask questions here and refere to https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines#no-weird-formatting-1

**Comment by ReenigneArcher** [comment]
Okay... this was confusing "full stop" is not a word we use in North America. "Period" is what we use. May want to update your docs.
